import streamlit as st

st.title("DATA STRUCTURE AND ALGORITHM. \n")
st.subheader("Ques1->WHAT IS DATA STRUCTURE. \n")
st.text("Ans1->Data structure is a way of organising and storing data in computer and use it effectively. \n")
st.subheader("# There are manily two types of Data Structure. \n")
st.subheader("1.LINEAR DATA STRUCTURE. \n")
st.text("1.Array->Array is a type of data structure which is used to store items in order. \n")
st.text("2.Linked list->Linked lsit is a type of data structure which is used to stores connected items. \n")
st.text("3.Queue->Queue is a type of data structure in which data is stored according to first come first out(FIFO) principle. \n")
st.text("4.Stack->Stack is a type of data structure in which data is stored according to last in,first out(LIFO) principle. \n")
st.subheader("2.NON-LINEAR DATA STRUCTURE. \n")
st.text("1.Tree->Tree is a type of data structure in which data is stored in hierarchical structure. \n") 
st.text("2.Graph->Graph is a type of data structure in which data is not stored in hierarchical structure. \n")
st.title("ALGORITHM \n")
st.text("# An algorithm is a step-by-step procedure used to solve a problem or perform a task.")
st.title("Types of Algorithm \n")
st.text("1.Greedy Algorithm->Greedy algorithm is used to make the best local choice at each step. \n")
st.text("2.Divide and conquer->Divide and conquer is used to divide the problem into smaller subproblems and solve them easliy.\n")
st.text("3.Backtracking->Backtracking is used to build solution incrementally and backtracks when a choice is invalid.\n")
st.text("4.Recursive Algroithm->Recursive is used to solve problem by calling itself into smaller units.\n")
st.subheader("Types of control structure in algorithm \n")
st.text("1.sequence structure->In this structure statements are solved one after another in order.\n")
st.text("2.Branching(selection)->In this structure statements are solved based on conditions \n")
st.text("3.Loop(Repeation)->In this structure statements are solved by repeat of set of statements.\n")
st.markdown("---")
st.write("created by ujjwal mishra \n")
